workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

image: docker

stages:
  - check
  - decide

cache:
  key: btt_${CI_COMMIT_REF_NAME}
  paths:
    - EXISTING

check:
  stage: check
  image: alpine
  artifacts:
    paths:
      - build.yml
    expire_in: 3 hours
  before_script:
    - apk add bash
    - mv noop.template.yml build.yml
  script:
    - ./check.sh

decide:
  stage: decide
  trigger:
    include:
      - artifact: build.yml
        job: check
    strategy: depend
