workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

image: docker

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled

.build-template:
  stage: build
  services:
    - name: docker:dind
      command: ["--experimental"]
  before_script:
    - apk add --no-cache git
    - git fetch
    - git worktree add src master
    - mv entrypoint.sh src
  script:
    - ./build.sh

build:amd64:
  extends: .build-template
  variables:
    ARCH: amd64
build:arm/v7:
  extends: .build-template
  variables:
    ARCH: arm/v7
build:arm64:
  extends: .build-template
  variables:
    ARCH: arm64

deploy:
  stage: deploy
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - apk add --no-cache git
    - git fetch
  script:
    - ./manifest.sh $(git rev-parse origin/master | cut -c -7)
