image: docker

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  BUILDX_VER: 0.4.1

build:
  stage: build
  services:
    - name: docker:dind
      command: ["--experimental"]
  before_script:
    - apk add --no-cache git
    - git fetch
    - git checkout -f origin/master . .
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v${BUILDX_VER}/buildx-v${BUILDX_VER}.linux-amd64
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --name builder
    - docker buildx inspect --bootstrap builder
  script:
    - docker buildx build --cache-to=type=local,dest=cache,mode=max --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${REGISTRY_IMAGE}:latest -t ${REGISTRY_IMAGE}:$(git rev-parse origin/master | cut -c -7) .
    - echo ${TOKEN} | docker login -u ${USERNAME} --password-stdin ${REGISTRY}
    - docker buildx build --push --cache-from=type=local,src=cache --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${REGISTRY_IMAGE}:latest -t ${REGISTRY_IMAGE}:$(git rev-parse origin/master | cut -c -7) .
